myspace/blog/urls.py
from django.conf.urls import url
from blog import views

app_name='blog'


urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)/$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    url(r'^post/(?P<pk>\d+)/update/$',views.PostUpdateView.as_view(),name='post_update'),
    url(r'^post/(?P<pk>\d+)/delete/$',views.PostDeleteView.as_view(),name='post_delete'),
    url(r'^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post,name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve,name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),
]

myspace/myspace/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views

app_name = 'blog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    url(r'accounts/login/$',views.LoginView.as_view(),name='login'),
    url(r'accounts/logout/$',views.LogoutView.as_view(),name='logout',kwargs={'next_page':'/'})
]

myspace/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True,null= True)

    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

    

myspace/blog/forms.py
from django import forms
from django.forms import fields, widgets
from blog.models import Post,Comment

class PostForm(forms.ModelForm):
    
    class Meta():
        model = Post
        fields = ('author','title','text')

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author','text')

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textareas'})
        }

myspace/blog/views.py
from django.forms import forms
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog.models import Post,Comment
from blog.forms import PostForm,CommentForm
from django.urls import reverse_lazy,reverse

# Create your views here.

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date')
    
    def get_absolute_url(self):
        return reverse("blog:post_detail",kwargs={'pk':self.pk})

class PostDetailView(DetailView):
    model = Post

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.hmtl'
    form_class = PostForm 
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.hmtl'
    form_class = PostForm 
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_absolute_url(self):
        return reverse("blog:post_detail",kwargs={'pk':self.pk})
    

    def get_queryset(self):
        return Post.objects.filter(publish_date__isnull=True).order_by('create_date')

    






####################################################################################################################################################################################################################################
@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('post_detail',pk=pk)


@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail' , pk=post.pk)
    else:
        form = CommentForm()
    return render(request,'blog/comment_form.html',{'form':form})

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment,pk)
    comment.approve()
    return redirect('post_detail',pk=comment.post.pk)

@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail',pk=post_pk)

myspace/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
<h1 class="abh">Hey! Thanks for checking this page out</h1>
{% endblock %} 

myspace/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Space - fill it out and have fun</title>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- medium style editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/blog.css'%}">
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <section class="navigation">
            <div class="nav-container">
              <div class="brand">
                <a href="{% url 'blog:post_list' %}">My Space</a>
              </div>
              <nav>
                <div class="nav-mobile"><a id="nav-toggle" href="#!"></a></div>
                <ul class="nav-list">
                  <li>
                    <a href="{% url 'blog:post_list' %}">Home</a>
                  </li>
                  <li>
                    <a href="{% url 'blog:about' %}">About</a>
                  </li>
                  <li>
                    <a href="#!">Contact</a>
                  </li>
                  <li>
                    {% if user.is_authenticated %}
                      <li>
                        <a href="{% url 'blog:post_new' %}">New Post</a>
                      </li>
                      <li>
                        <a href="{% url 'blog:post_draft_list' %}">Drafts</a>
                      </li>
                      <li>
                        <a href="{% url 'logout' %}">Log Out</a>
                      </li>
                      <li>
                        <a>Welcome:{{ user.username }}</a>
                      </li>
                      {% else %}
                      <li>
                        <a href="{% url 'login' %}">Login</a>
                      </li>
                      {% endif %}
                </ul>
              </nav>
            </div>
          </section>
    </header>
    <!-- content block -->
    <main>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog_posts">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer>


    </footer>
    
</body>
</html>

myspace/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% block content %}
<h1>New Comment</h1>
<form class="save" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class=" save btn btn-default"> Post Comment </button>
</form>
<script> var editor = new MediumEditor('.editable'); </script>
{% endblock %} 

myspace/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure want to delete {{ object }} ? </p>
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock %} 

myspace/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<h1 class="title">{{ post.title }}</h1>
{% if post.publish_date %}
<div class="postdate">
    {{ post.publish_date }}
</div>
{% else %}
<a class="btn btn-primary" href="{% url 'post_publish' pk=post.pk %}">Publish</a>
{% endif %}

<p class="postcontent">{{ post.text|safe|linebreaksbr}}</p>
{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'post_edit' pk=post.pk %}">
    <span class="glyphicon glyphicon-pencil"></span>
</a>
<a class="btn btn-primary" href="{% url 'post_remove' pk=post.pk %}">
    <span class="glyphicon glyphicon-remove"></span>
</a>
{% endif %}

<hr>
<a class="btn btn-primary btn-comment " href="{% url 'add_comment_to_post' pk=post.pk %}"></a>
<div class="container">
    {% for comment in post.comments.all %}
    <br>
    {% if user.is_authenticated or comment.approver_comment %}
    {{ comment.created_date }}
    {% if not comment.approved_comment%}
    <a class="btn btn-primary" href="{% url 'comment_remove' pk=comment.pk %}">
        <span class="glyphicon glyphicon-remove"></span>
    </a>
    <a class="btn btn-primary" href="{% url 'comment_approve' pk=comment.pk %}">
        <span class="glyphicon glyphicon-ok"></span>
    </a>
    {% endif %}
    <p>{{ comment.text|safe|linebreaks}}</p>
    <p>Posted By : {{ comment.author }}</p>g
    {% endif %}
    {% empty %}
    <p>No Comments </p>
    {% endfor %}
</div>
{% endblock %} 

myspace/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}
{% block content %}

<div class="post">
    <p class="date"> Created: {{ post.created_date|date:'d-m-Y'}}</p>
    <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    <p>{{ post.text|truncatechars:200}}</p>
</div>
{% endblock %} 

myspace/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
<h1>New Post</h1>
<form class="save" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class=" save btn btn-default"> Save </button>
</form>
<script> var editor = new MediumEditor('.editable'); </script>
{% endblock %} 

myspace/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
<div class="centerstage">
    {% for post in post_list %}
    <div class="post">
        <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <div class="date">
            <p>Published on : {{post.published|date:"D M Y"}}</p>
        </div>
        <a href="{% url 'post_detail' pk=post.pk %}">Comments : {{ post.approve_comments }}</a>
    </div>
    {% endfor %}
</div>
{% endblock %} 